import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import Navbar from '../components/Navbar';

const inter = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400'],
});

export const metadata: Metadata = {
  title: 'Disney+',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <Navbar />
          {children}
        </>
      </body>
    </html>
  );
}
